import { useState } from "react"
import { useApp } from "../context"
import { PATIENTS } from "../data/mock"

type SummarySection = { id: string; label: string; source: "Interview" | "Records" | "Both"; content: string }

const initialSections: SummarySection[] = [
  { id: "chief", label: "Chief complaint", source: "Interview", content: "Persistent dry cough with mild breathlessness on exertion and an unintentional 4 kg weight loss." },
  { id: "hpi", label: "History of present illness", source: "Both", content: "Cough began approximately 3 months ago and has gradually become more frequent. No hemoptysis, fever, or acute chest pain reported. Patient notes reduced appetite and fatigue. Chest CT performed today after an abnormal chest X-ray at an outside clinic." },
  { id: "past", label: "Past history", source: "Records", content: "Hypertension for 8 years, reported controlled on medication. No documented diabetes, tuberculosis, asthma, COPD, or prior malignancy. Appendectomy in 2004." },
  { id: "drugs", label: "Drugs / allergies", source: "Both", content: "Amlodipine 5 mg once daily. No known drug allergies reported." },
  { id: "family", label: "Family history", source: "Interview", content: "Father had ischemic heart disease. No known family history of lung cancer or tuberculosis." },
  { id: "personal", label: "Personal history", source: "Interview", content: "Former smoker: approximately 12 pack-years; stopped 9 years ago. No alcohol use. Lives with spouse and is independent in activities of daily living." },
  { id: "ros", label: "Review of systems", source: "Interview", content: "Positive: fatigue, appetite reduction, dry cough, exertional breathlessness. Negative: fever, chills, hemoptysis, night sweats, orthopnea, leg swelling, or recent travel." },
  { id: "investigations", label: "Investigations", source: "Records", content: "Chest X-ray (08 Sep): right lower-zone opacity, further evaluation advised. CT Chest (today): 8 mm right lower-lobe pulmonary nodule; no acute consolidation. CBC from outside lab (08 Sep): Hb 12.8 g/dL, WBC 7,800/uL." },
]

const sourceStyle = { Interview: { bg: "#EFF6FF", color: "#1D4ED8" }, Records: { bg: "#F5F3FF", color: "#7C3AED" }, Both: { bg: "#F0FDF4", color: "#15803D" } }

export function ClinicalSummary() {
  const { setView } = useApp()
  const patient = PATIENTS.find((item) => item.id === "p2")!
  const [sections, setSections] = useState(initialSections)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [decision, setDecision] = useState<"draft" | "approved" | "returned">("draft")
  const [showTranscript, setShowTranscript] = useState(false)
  const updateSection = (id: string, content: string) => setSections((current) => current.map((section) => section.id === id ? { ...section, content } : section))
  const status = decision === "approved" ? { label: "Approved by clinician", bg: "#F0FDF4", color: "#15803D" } : decision === "returned" ? { label: "Returned for revision", bg: "#FFF7ED", color: "#C2410C" } : { label: "Awaiting clinician review", bg: "#FFFBEB", color: "#A16207" }

  return <div className="min-h-full bg-[#F8FAFC]"><div className="mx-auto max-w-[1440px] px-4 py-5 sm:px-6 lg:px-8">
    <div className="mb-5 flex flex-col justify-between gap-4 xl:flex-row xl:items-center"><div><div className="mb-2 flex items-center gap-2 text-xs font-medium"><button onClick={() => setView("doctor-dashboard")} className="text-slate-500 hover:text-blue-700">My queue</button><span className="text-slate-300">/</span><span className="text-slate-500">Patient summary</span></div><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><h1 className="text-xl font-semibold tracking-tight text-slate-900">Clinical summary</h1><span className="font-mono text-xs text-slate-400">AI-DRAFT-0241</span><span className="rounded-full px-2.5 py-1 text-[11px] font-semibold" style={{ background: status.bg, color: status.color }}>{status.label}</span></div><p className="mt-1 text-sm text-slate-500">Generated from patient interview and 3 verified medical documents. This is a clinical handover, not a diagnosis.</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={() => setDecision("returned")} className="rounded-md border border-slate-200 bg-white px-3.5 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50">Return for revision</button><button onClick={() => setDecision("approved")} className="rounded-md bg-blue-700 px-3.5 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-800">Approve & add to record</button></div></div>
    <div className="mb-5 grid gap-3 rounded-lg border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-4"><div className="flex items-center gap-3 border-b border-slate-100 pb-3 sm:border-b-0 sm:border-r sm:pb-0 xl:border-r"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-50 text-sm font-bold text-blue-700">PS</div><div><div className="font-semibold text-slate-900">{patient.name}</div><div className="text-xs text-slate-500">{patient.age} years · Female · ABHA linked</div></div></div><Meta label="ABHA address" value="priya.shah@abdm" /><Meta label="Interview" value="Completed · English" /><Meta label="Consent" value="Granted · 14 Sep, 10:14" success /></div>
    <div className="grid gap-5 xl:grid-cols-[250px_minmax(0,1fr)_285px]"><aside className="space-y-4 xl:sticky xl:top-4 xl:self-start"><div className="rounded-lg border border-slate-200 bg-white p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-900">Source material</h2><span className="text-xs text-slate-400">4 items</span></div><div className="space-y-2"><SourceItem label="AI interview" detail="10 min · completed" kind="Interview" active onClick={() => setShowTranscript((open) => !open)} /><SourceItem label="CT chest report" detail="Today · verified" kind="Records" /><SourceItem label="Chest X-ray referral" detail="08 Sep · verified" kind="Records" /><SourceItem label="Outside lab report" detail="08 Sep · verified" kind="Records" /></div></div><div className="rounded-lg border border-blue-100 bg-blue-50 p-4"><div className="mb-1 text-xs font-semibold uppercase tracking-wider text-blue-700">Triage note</div><p className="text-sm leading-5 text-blue-950">No interview red flags identified. Review imaging finding and outside referral before disposition.</p></div></aside>
      <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">Doctor-ready handover</h2><p className="mt-0.5 text-xs text-slate-500">Review, amend, then approve. Sources are tagged for traceability.</p></div><div className="divide-y divide-slate-100">{sections.map((section) => { const isEditing = editingId === section.id; const style = sourceStyle[section.source]; return <article key={section.id} className="group px-5 py-4"><div className="mb-2 flex items-center gap-2"><h3 className="text-xs font-semibold uppercase tracking-widest text-slate-500">{section.label}</h3><span className="rounded px-1.5 py-0.5 text-[10px] font-semibold" style={{ background: style.bg, color: style.color }}>{section.source}</span><button onClick={() => setEditingId(isEditing ? null : section.id)} className="ml-auto text-xs font-medium text-blue-700 opacity-100 transition-opacity sm:opacity-0 sm:group-hover:opacity-100">{isEditing ? "Done" : "Edit"}</button></div>{isEditing ? <textarea autoFocus value={section.content} onChange={(event) => updateSection(section.id, event.target.value)} className="min-h-24 w-full rounded-md border border-blue-300 bg-blue-50/40 p-3 text-sm leading-6 text-slate-700 outline-none ring-blue-100 focus:ring-2" /> : <p className="text-sm leading-6 text-slate-700">{section.content}</p>}</article> })}</div></section>
      <aside className="space-y-4 xl:sticky xl:top-4 xl:self-start"><div className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="mb-3 text-sm font-semibold text-slate-900">Key takeaways</h2><div className="space-y-3 text-sm"><Takeaway title="Symptoms" text="Cough for 3 months with weight loss and fatigue." /><Takeaway title="Relevant history" text="Former smoker; hypertension on amlodipine." /><Takeaway title="Documented finding" text="8 mm right lower-lobe pulmonary nodule on today’s CT." accent="amber" /></div></div><div className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="mb-3 text-sm font-semibold text-slate-900">Provenance</h2><div className="space-y-3 border-l-2 border-slate-100 pl-3 text-xs text-slate-500"><p><span className="font-medium text-slate-700">10:14</span> Consent captured</p><p><span className="font-medium text-slate-700">10:19</span> Interview completed</p><p><span className="font-medium text-slate-700">10:22</span> 3 documents extracted</p><p><span className="font-medium text-slate-700">10:23</span> Draft summary generated</p></div></div></aside>
    </div></div>{showTranscript && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-4 sm:items-center" onClick={() => setShowTranscript(false)}><div className="w-full max-w-xl rounded-xl bg-white p-5 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">Interview transcript</h2><p className="text-xs text-slate-500">English · completed at 10:19</p></div><button className="text-slate-400 hover:text-slate-700" onClick={() => setShowTranscript(false)}>Close</button></div><div className="space-y-3 text-sm leading-6"><p><span className="font-semibold text-blue-700">Assistant:</span> What brings you in today?</p><p><span className="font-semibold text-slate-700">Priya:</span> I have had a dry cough for about three months. I feel tired and get breathless when I climb stairs.</p><p><span className="font-semibold text-blue-700">Assistant:</span> Have you noticed fever, blood in the cough, or chest pain?</p><p><span className="font-semibold text-slate-700">Priya:</span> No. I have also lost about four kilograms without trying.</p></div></div></div>}</div>
}

function Meta({ label, value, success = false }: { label: string; value: string; success?: boolean }) { return <div className="pl-0 sm:pl-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 text-sm font-medium" style={{ color: success ? "#15803D" : "#334155" }}>{value}</div></div> }
function SourceItem({ label, detail, kind, active, onClick }: { label: string; detail: string; kind: "Interview" | "Records"; active?: boolean; onClick?: () => void }) { const style = sourceStyle[kind]; return <button onClick={onClick} className="flex w-full items-center gap-2 rounded-md p-2 text-left hover:bg-slate-50" style={{ background: active ? "#F8FAFC" : undefined }}><span className="h-2 w-2 rounded-full" style={{ background: style.color }} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-slate-700">{label}</span><span className="block text-[11px] text-slate-400">{detail}</span></span></button> }
function Takeaway({ title, text, accent }: { title: string; text: string; accent?: "amber" }) { return <div className={accent ? "rounded-md border border-amber-100 bg-amber-50 p-2.5" : ""}><div className="mb-0.5 text-xs font-semibold text-slate-700">{title}</div><p className="leading-5 text-slate-500">{text}</p></div> }
